name: hsf-india
channels:
  - pytorch
  - nvidia/label/cuda-13.2
  - conda-forge
dependencies:
  - python=3.14
  - aiohttp
  - astunparse
  - awkward
  - bash_kernel
  - bitsandbytes
  - clang-tools
  - cxx-compiler
  - dask
  - datasets
  - distributed
  - graphviz
  - grpcio
  - hdf5
  - hepunits
  - hist
  - ipympl
  - jupyterlab-deck
  - jupyterlab-mathjax3
  - lz4
  - matplotlib
  - cuda-nvcc
  - numba
  #- numpy<2  # pinned in ml branch; commented out for broader compatibility
  - openssh
  - pandas
  - particle
  - peft
  - pint
  - pip
  - polars
  - pyarrow
  - pybind11
  - pyhf
  - pympler
  - pyshp
  - py-spy
  - pytorch
  - pytorch-cuda=12.8
  - python-graphviz
  - requests
  - scikit-learn
  - scipy
  - torch-geometric
  - torchvision
  - transformers
  - trl
  - uproot
  - vector
  - vim
  - pip:
      - h5py
      - tensorboard
      - jax[cuda13]
      - nvidia-cudnn-cu13
      - optax
      - equinox
      - flax
      - xgboost
      - omnilearned
      - servicex

variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
